---
- name: Playbook to backup configs on Cisco Routers
  connection: network_cli
  hosts: device_roles_router
  hosts: device_roles_{ten Device Roles trong netbox}
  gather_facts: False

  tasks:
    - name: Show Running configuration on Device
      ios_command:
        commands:
          - show run
      register: config

    - name: Save output to backups folder
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "./backups/{{ inventory_hostname }}-config.txt"


# ansible-playbook backups_playbook.yml -u admin  -k
# Nhap password ssh cua thiet bi
# https://journey2theccie.wordpress.com/2020/03/25/automating-my-ccie-lab-pt-2-ansible-overview-backups-and-netbox-integration/
