---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "hosts.yaml"
        group_file: "groups.yaml"
        defaults_file: "defaults.yaml"
runners:
    plugin: threaded
    options:
        num_workers: 100 #co the chay toi da cung luc 100 thiet bi